language: cpp
sudo: false
dist: bionic

notifications:
  slack: c0demonk3ys:gnjXYwuoMOBnffg9h8YnlLyE

git:
  depth: 5

matrix:
  include:
    - name: "GCC (Debug, ThirdParty)"
      os: linux
      compiler: gcc
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test', 'kalakris-cmake' ]
          packages: [ 'g++-7', 'libstdc++-7-dev', 'ninja-build', 'cmake', 'xorg-dev', 'libglu1-mesa-dev' ]
      env: CMAKE_BUILD_TYPE=DEBUG

    - name: "GCC (Debug, System)"
      os: linux
      compiler: gcc
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test', 'kalakris-cmake' ]
          packages: [ 'g++-7', 'libstdc++-7-dev', 'ninja-build', 'cmake', 'xorg-dev', 'libglu1-mesa-dev', 'libglfw3-dev' ]
      env: CMAKE_BUILD_TYPE=DEBUG

    - name: "GCC (Release, ThirdParty)"
      os: linux
      compiler: gcc
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test', 'kalakris-cmake' ]
          packages: [ 'g++-7', 'libstdc++-7-dev', 'ninja-build', 'cmake', 'xorg-dev', 'libglu1-mesa-dev' ]
      env: CMAKE_BUILD_TYPE=RELEASE

    - name: "GCC (Release, System)"
      os: linux
      compiler: gcc
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test', 'kalakris-cmake' ]
          packages: [ 'g++-7', 'libstdc++-7-dev', 'ninja-build', 'cmake', 'xorg-dev', 'libglu1-mesa-dev', 'libglfw3-dev' ]
      env: CMAKE_BUILD_TYPE=RELEASE

    - name: "Clang (Debug, ThirdParty)"
      os: linux
      compiler: clang
      addons:
        apt:
          sources: [ 'llvm-toolchain-xenial-6.0', 'ubuntu-toolchain-r-test', 'kalakris-cmake' ]
          packages: [ 'clang-6.0', 'libstdc++-7-dev', 'ninja-build', 'cmake', 'xorg-dev', 'libglu1-mesa-dev' ]
      env: CMAKE_BUILD_TYPE=DEBUG

    - name: "Clang (Debug, System)"
      os: linux
      compiler: clang
      addons:
        apt:
          sources: [ 'llvm-toolchain-xenial-6.0', 'ubuntu-toolchain-r-test', 'kalakris-cmake' ]
          packages: [ 'clang-6.0', 'libstdc++-7-dev', 'ninja-build', 'cmake', 'xorg-dev', 'libglu1-mesa-dev', 'libglfw3-dev' ]
      env: CMAKE_BUILD_TYPE=DEBUG

    - name: "Clang (Release, ThirdParty)"
      os: linux
      compiler: clang
      addons:
        apt:
          sources: [ 'llvm-toolchain-xenial-6.0', 'ubuntu-toolchain-r-test', 'kalakris-cmake' ]
          packages: [ 'clang-6.0', 'libstdc++-7-dev', 'ninja-build', 'cmake', 'xorg-dev', 'libglu1-mesa-dev' ]
      env: CMAKE_BUILD_TYPE=RELEASE

    - name: "Clang (Release, System)"
      os: linux
      compiler: clang
      addons:
        apt:
          sources: [ 'llvm-toolchain-xenial-6.0', 'ubuntu-toolchain-r-test', 'kalakris-cmake' ]
          packages: [ 'clang-6.0', 'libstdc++-7-dev', 'ninja-build', 'cmake', 'xorg-dev', 'libglu1-mesa-dev', 'libglfw3-dev' ]
      env: CMAKE_BUILD_TYPE=RELEASE

before_install:
  - env
  - export SRC_DIR="`pwd`"
  - if [ "$CXX" = "g++" ]; then export CXX="g++-7" CC="gcc-7"; export J=1; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-6.0" CC="clang-6.0"; fi

script:
  - $CXX --version
  - cmake --version
  - cd "$TRAVIS_BUILD_DIR/build"
  - pwd
  - cmake -Dstdlib=libstdc++ -DVERBOSE_LOGGING=ON -G "Unix Makefiles" "$SRC_DIR"
  - make -j$J
